### ISSUE TITLE
Error message when running from docker-container.

### ISSUE THREAD

**Issue by Fffrank** [xur17/southwest-alerts#4]
compose file: 
```
  southwest-alerts:
    image: xur17/southwest-alerts
    container_name: southwest-alerts
    environment:
      - MAILGUN_DOMAIN=XXX.mailgun.org
      - MAILGUN_API_KEY=XXX
      - USERNAME1=XXXXXXX
      - PASSWORD1=XXXXX
      - EMAIL1=XXXX@gmail.com
```

compose log:
```
dietpi@DietPi:/$ dcp logs southwest-alerts
Attaching to southwest-alerts
southwest-alerts    | standard_init_linux.go:190: exec user process caused "exec format error"
dietpi@DietPi:/$
```
